version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - apt install unzip -y
      - pip install -r requirements.txt -t lib
      - wget https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
      - unzip terraform_1.1.8_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - cd ./terraform-code
      - terraform init
  build:
    commands:
      - if [ $${TF_ACTION} == "apply" ]; then terraform apply; fi
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../Lambda_CODEBUILD_BUILD_NUMBER.zip .
      - cd ..
      - zip -g Lambda_$CODEBUILD_BUILD_NUMBER.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name $TF_LAMBDA_FUNCTION_NAME --zip-file fileb://Lambda_$CODEBUILD_BUILD_NUMBER.zip
      - echo "Lambda updated successfully!"
