version: 0.2
env:
  variables:
    - lambda_artifact: "lambda_artifact.zip"
phases:
  install:
    runtime-versions:
      python: 3.8
    on-failure: ABORT
    commands:
      - echo "Getting started with AWS Lambda deployment number ${CODEBUILD_BUILD_NUMBER}..."
      - echo "Installing dependencies..."
      - apt install unzip -y
      - pip install -r requirements.txt -t lib
      - wget https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
      - unzip terraform_1.1.8_linux_amd64.zip && mv terraform /usr/local/bin/
  pre_build:
    on-failure: ABORT
    commands:
      - cd ./terraform-code
      - terraform init
  build:
    on-failure: ABORT
    commands:
      - echo "Zipping deployment package..."
      - cd ../.build/
      - chmod 644 lambda_function.py
      - zip ${lambda_artifact} lambda_function.py
      - ls && pwd
      - mkdir -p unzip
      - unzip ${lambda_artifact} -d unzip
      - ls -l unzip
      - cd ../terraform-code/
      - echo "Starting Terraform plan..."
      - terraform plan
  post_build:
    on-failure: ABORT
    commands:
      - echo "Deploying new Lambda function..."
      #- if [ $${TF_ACTION} == "apply" ]; then terraform apply; fi
      - echo "Starting Terraform apply..."
      - terraform apply -auto-approve
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name ${TF_VAR_lambda_function_name} --zip-file fileb://${lambda_artifact}
      - echo "Lambda updated successfully!"