version: 2

jobs:
  build:
    working_directory: /tmp/project/
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: build lambda
          command: |
            echo "Getting started with AWS Lambda deployment..."
            echo "Installing dependencies..."
            apt update -y && apt install -y zip
            echo "Zipping deployment package..."
            cd ./.build/
            zip lambda_artifact.zip lambda_function.py
      - store_artifacts:
          path: ./.build/lambda_artifact.zip
          destination: lambda_artifact.zip
      - persist_to_workspace:
          root: .
          paths:
            - .
  plan-apply:    
    working_directory: /tmp/project/
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            echo "Starting Terraform init and plan..."
            echo "Installing dependencies..."
            apt update -y 
            apt install -y curl unzip wget
            wget https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
            unzip terraform_1.1.8_linux_amd64.zip && mv terraform /usr/local/bin/
            echo "Getting artifact..."
            cd ./terraform-code/
            curl -H "Circle-Token: $var_circleci_api_access" https://circleci.com/api/v1.1/project/github/benjaminvaliente/github-lambda-poc/latest/artifacts \
            | grep -o 'https://[^"]*' \
            | wget --verbose --header "Circle-Token: $var_circleci_api_access" --input-file -
            echo "Starting terraform init..."
            terraform --version
            terraform init -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
            echo "Starting terraform plan..."
            terraform plan -out tfapply -var-file variables.tf
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    working_directory: /tmp/project/
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: terraform apply
          command: |
            echo "Deploying terraform changes..."
            echo "Installing dependencies..."
            apt update -y 
            apt install -y curl unzip wget
            wget https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
            unzip terraform_1.1.8_linux_amd64.zip && mv terraform /usr/local/bin/
            echo "Getting artifact..."
            cd ./terraform-code/
            curl -H "Circle-Token: $var_circleci_api_access" https://circleci.com/api/v1.1/project/github/benjaminvaliente/github-lambda-poc/latest/artifacts \
            | grep -o 'https://[^"]*' \
            | wget --verbose --header "Circle-Token: $var_circleci_api_access" --input-file -
            echo "Starting terraform apply..."
            terraform apply -auto-approve tfapply -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
      - persist_to_workspace:
          root: .
          paths:
            - .
  approve-deploy:
    docker:
      - image: ubuntu:20.04
    steps:
      - attach_workspace:
          at: .
      - run:
          name: deploy
          command: |        
            echo "Waiting for approval..."
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: /tmp/project/
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: deploy
          command: |        
            echo "Updating Lambda function..."
            echo "Installing dependencies..."
            apt update -y 
            apt install -y curl unzip wget
            wget https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
            unzip terraform_1.1.8_linux_amd64.zip && mv terraform /usr/local/bin/
            echo "Configuring AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
            echo "Getting artifact..."
            ls -la && pwd
            cd ./terraform-code/
            curl -H "Circle-Token: $var_circleci_api_access" https://circleci.com/api/v1.1/project/github/benjaminvaliente/github-lambda-poc/latest/artifacts \
            | grep -o 'https://[^"]*' \
            | wget --verbose --header "Circle-Token: $var_circleci_api_access" --input-file -
            echo "Deploying Lambda artifact..."
            aws lambda update-function-code --function-name $var_lambda_function_name --zip-file fileb://lambda_artifact.zip --profile default
            echo "Lambda updated successfully!"  
      - persist_to_workspace:
          root: .
          paths:
            - .
  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -var-file variables.tf
      - persist_to_workspace:
          root: .
          paths:
            - .
  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - build
      - plan-apply:
          requires: 
            - build  
      - approve-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - approve-apply
      - approve-deploy:
          type: approval
          requires:
            - apply
      - deploy:
          requires:
            - approve-deploy
      - plan-destroy:
          requires:
            - apply
      - approve-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - approve-destroy
      